build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "luabridge/2.4.1"
    CONAN_USERNAME: "utopia"
    CONAN_LOGIN_USERNAME: "konradnotantoo"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/konradnotantoo/utopia"
    CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
    CONAN_BUILD_POLICY: "missing"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
