build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "luabridge/2.6"
    CONAN_USERNAME: "utopia"
    CONAN_LOGIN_USERNAME: "konrad"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://utopia.jfrog.io/artifactory/api/conan/utopia-conan"
    CONAN_BUILD_POLICY: "missing"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_REVISIONS_ENABLED: 1
          CONAN_VISUAL_VERSIONS: 16
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
          CONAN_REVISIONS_ENABLED: 1
          CONAN_VISUAL_VERSIONS: 17


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
